name: Build web app

on:
  workflow_call:
    inputs:
      artifact-retention-days:
        description: Passed to 'retention-days' of actions/upload-artifact. When less than 0, it means skipping upload.
        type: number
        required: false
        default: -1
      build-dir:
        description: Define the directory where built files will be placed.
        type: string
        required: false
        default: .output
      node-env:
        description: NODE_ENV
        type: string
        required: false
        default: production
      node-modules-cache-key:
        description: Passed to 'key' of actions/cache/restore for restoring node_modules directory.
        type: string
        required: true
      node-modules-path:
        description: Passed to 'path' of actions/cache/restore for restoring node_modules directory.
        type: string
        required: true
      node-version:
        description: Passed to 'node-version' of actions/setup-node.
        type: string
        required: true
    outputs:
      artifact-name:
        description: A value to pass to 'name' of actions/download-articaft.
        value: ${{ jobs.build.outputs.artifact-name }}
      artifact-path:
        description: A value to pass to 'path' of actions/download-articaft.
        value: ${{ inputs.build-dir }}

env:
  NODE_ENV: ${{ inputs.node-env }}

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-name: ${{ steps.artifact-name.outputs.value }}
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - uses: actions/cache/restore@v4
        with:
          key: ${{ inputs.node-modules-cache-key }}
          path: ${{ inputs.node-modules-path }}

      - run: yarn run build

      - id: artifact-name
        name: Define artifact name
        run: echo "value=build-app-${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - if: ${{ inputs.artifact-retention-days >= 0 }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.artifact-name.outputs.value }}
          path: ${{ inputs.build-dir }}
          retention-days: ${{ inputs.artifact-retention-days }}
